manette_v1 : manette_v1.cpp library\ceSerial.h
	g++ manette_v1.cpp library\ceSerial.cpp -o manette_v1.exe -std=c++11

manette_v2 : manette_v2.cpp library\ceSerial.h
	g++ manette_v2.cpp library\ceSerial.cpp -o manette_v2.exe -std=c++11